version: "3.7"
# Define a versão da sintaxe do arquivo docker-compose.yml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    # Define a configuração do serviço web

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Define a configuração do serviço de banco de dados

volumes:
  postgres_data:
  # Define o volume para armazenar os dados do banco de dados
